require('config.colorscheme')
require('config.completion')
require('config.fugitive')
require('config.treesitter')
require('config.lualine')
require('config.nvim-web-dev-icons')
require('config.nvim-tree')
require('config.comment')
require('config.barbar')
require('config.telescope')
-- require('config.format')
require('config.lsp')
